version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres-16
    env_file:
      - ./.env.development.local
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data